version: '3.7'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile-Postgres
    image: server-db:latest
    container_name: server-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  GITUSER: ${GITUSER}
      #  GITEMAIL: ${GITEMAIL}
      #  GITHUBPAT: ${GITHUBPAT}
    image: server-app:latest
    container_name: server-app
    volumes:
      - ./:/var/www/app
    ports:
      - 5000:5000
    links:
      - database
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWD=password
      - DB_PORT=5432
      - DB_DB=postgres
      - DB_LIMIT=400
    command:
      sh -c 'npm i && npx nodemon index.js'
